id: P010711
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1659
  title: མན་ངག་བཀའ་རྒྱ་མ།
  author: ''
  volumes:
    7759a6dec86842fca5970e7d8ed5643b:
      image_group_id: I1KG1750
      title: ''
      volume_number: 1
      total_pages: 692
      base_file: v001.txt
