id: I943A661F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:32:38+00:00'
last_modified: '2022-06-08T16:58:49.752418+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1659
  title: མན་ངག་བཀའ་རྒྱ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    99D5:
      image_group_id: I1KG1750
      title: ''
      total_pages: 692
      order: 1
      base_file: 99D5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
